apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    app: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.47.1
          ports:
            - containerPort: 8080
          args:
            - "--disable_metrics=udp,percpu,sched,tcp,udp,process"