version: '3.8'

services:
  infra-demo-app:
    container_name: infra-demo-app
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=infra-demo-db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=mydb
    depends_on:
      - infra-demo-db

  infra-demo-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9191:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - infra-demo-app
      - node-exporter
      - cadvisor

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - "9100:9100"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

volumes:
  grafana_data:
