- name: Install Docker dependencies
  apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable

- name: Install Docker
  apt:
    name: docker-ce
    update_cache: yes

- name: Install Docker Compose V2
  shell: |
    mkdir -p ~/.docker/cli-plugins
    curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
    chmod +x ~/.docker/cli-plugins/docker-compose
  args:
    creates: ~/.docker/cli-plugins/docker-compose

- name: Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes
